### ISSUE TITLE
Update view first

### ISSUE THREAD

**Issue by Xosmond** [raen79/fie#19]
I wanted to propose to update the view first and then confirm the change, deciding to keep or undo the action on view, this to avoid the delay on the view update.

**Comment by raen79** [comment]
There isn't much of a delay at the moment. Where are you experiencing a delay exactly? At the moment there is a delay placed on purpose when modifying the value of a variable within an input. It is there on purpose so that the view only updates when the user stops typing. Is this what you are talking about?

**Comment by raen79** [comment]
Hmm, the biggest issue I see with this is that it would require a lot of frontend code and then this would just become angular where the state is only persisted in the backend. I think if this is what we want then a simple API + JS framework is the solution.

N.B. the delay partly exists on purpose so that the user's input will not be overwritten on every key stroke. But I am working on it by making the input field the user is typing in protected.

N.B.2 The application is hosted in Frankfurt which might be affecting the performance depending on where you live.

**Comment by Xosmond** [comment]
Oh i see, I will check the code and see if it can be do it without a lot of code. Thanks for your response.
